# Table 5-3 AWWA M6 Manual

In [1]:
# Import libraries
import pandas as pd

### Displacement Meters

In [2]:
# Displacement Meters
size = [1/2, 5/8, 3/4, 1, 1 + 1/2, 2] #in
max_flow = [8, 15, 25, 40, 50, 100] #gpm
max_quant = [100, 100, 100, 100, 100, 100] #gal
max_limit_min = [98.5, 98.5, 98.5, 98.5, 98.5, 98.5] #%
max_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5, 101.5] #%
int_flow = [2, 2, 3, 4, 8, 15] #gpm
int_quant  = [10, 10, 10, 10, 100, 100] #gal
int_limit_min = [98.5, 98.5, 98.5, 98.5, 98.5, 98.5] #%
int_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5, 101.5] #%
min_flow = [1/4, 1/4, 1/2, 3/4, 1 + 1/2, 2] #gpm
min_quant  = [10, 10, 10, 10, 100, 100] #gal
min_limit_min = [95, 95, 95, 95, 95, 95] #%
min_limit_max = [101, 101, 101, 101, 101, 101] #%
displacement_meter = pd.DataFrame(index = size, data = {'max_flow': max_flow, 'max_quant': max_quant, 
                                    'max_limit_min': max_limit_min, 'max_limit_max': max_limit_max, 
                                    'int_flow': int_flow, 'int_quant': int_quant, 
                                    'int_limit_min': int_limit_min, 'int_limit_max': int_limit_max,
                                    'min_flow': min_flow, 'min_quant': min_quant, 
                                    'min_limit_min': min_limit_min, 'min_limit_max': min_limit_max,})
displacement_meter

,max_flow,max_quant,max_limit_min,max_limit_max,int_flow,int_quant,int_limit_min,int_limit_max,min_flow,min_quant,min_limit_min,min_limit_max
0.500,8,100,98.5,101.5,2,10,98.5,101.5,0.25,10,95,101
0.625,15,100,98.5,101.5,2,10,98.5,101.5,0.25,10,95,101
0.750,25,100,98.5,101.5,3,10,98.5,101.5,0.50,10,95,101
1.000,40,100,98.5,101.5,4,10,98.5,101.5,0.75,10,95,101
1.500,50,100,98.5,101.5,8,100,98.5,101.5,1.50,100,95,101
2.000,100,100,98.5,101.5,15,100,98.5,101.5,2.00,100,95,101

### Multijet Meters

In [3]:
# Multijet Meters
size = [5/8, 3/4, 1, 1 + 1/2, 2] #in
max_flow = [15, 25, 35, 70, 100] #gpm
max_quant = [100, 100, 100, 100, 100] #gal
max_limit_min = [98.5, 98.5, 98.5, 98.5,  98.5] #%
max_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5] #%
int_flow = [1, 2, 3, 5, 8] #gpm
int_quant = [10, 10, 10, 100, 100] #gal
int_limit_min = [98.5, 98.5, 98.5, 98.5,  98.5] #%
int_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5] #%
min_flow = [1/4, 1/2, 3/4, 1 + 1/2, 2] #gpm
min_quant = [10, 10, 10, 100, 100] #gal
min_limit_min = [97, 97, 97, 97, 97] #%
min_limit_max = [103, 103, 103, 103, 103] #%
multijet_meter = pd.DataFrame(index = size, data = {'max_flow': max_flow, 'max_quant': max_quant, 
                                    'max_limit_min': max_limit_min, 'max_limit_max': max_limit_max, 
                                    'int_flow': int_flow, 'int_quant': int_quant, 
                                    'int_limit_min': int_limit_min, 'int_limit_max': int_limit_max,
                                    'min_flow': min_flow, 'min_quant': min_quant, 
                                    'min_limit_min': min_limit_min, 'min_limit_max': min_limit_max,})
multijet_meter

,max_flow,max_quant,max_limit_min,max_limit_max,int_flow,int_quant,int_limit_min,int_limit_max,min_flow,min_quant,min_limit_min,min_limit_max
0.625,15,100,98.5,101.5,1,10,98.5,101.5,0.25,10,97,103
0.750,25,100,98.5,101.5,2,10,98.5,101.5,0.50,10,97,103
1.000,35,100,98.5,101.5,3,10,98.5,101.5,0.75,10,97,103
1.500,70,100,98.5,101.5,5,100,98.5,101.5,1.50,100,97,103
2.000,100,100,98.5,101.5,8,100,98.5,101.5,2.00,100,97,103

### Singlejet Meters

In [4]:
# Singlejet Meters
size = [5/8, 3/4, 1, 1 + 1/2, 2, 3,  4, 6] #in
max_flow = [15, 25, 40, 50, 100, 160, 250, 500] #gpm
max_quant = [100, 100, 100, 100, 100, 500, 500, 1000] #gal
max_limit_min = [98.5, 98.5, 98.5, 98.5,  98.5, 98.5, 98.5, 98.5] #%
max_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5] #%
int_flow = [2, 3, 4, 8, 15, 20, 40, 60] #gpm
int_quant = [10, 10, 10, 100, 100, 100, 100, 100] #gal
int_limit_min = [98.5, 98.5, 98.5, 98.5,  98.5, 98.5, 98.5, 98.5] #%
int_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5] #%
min_flow = [1/4, 1/2, 3/4, 1/2, 1/2, 1/2, 3/4, 1 + 1/2] #gpm
min_quant = [10, 10, 10, 100, 100, 100, 100, 100] #gal
min_limit_min = [95, 95, 95, 95, 95, 95, 95, 95] #%
min_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5] #%
singlejet_meter = pd.DataFrame(index = size, data = {'max_flow': max_flow, 'max_quant': max_quant, 
                                    'max_limit_min': max_limit_min, 'max_limit_max': max_limit_max, 
                                    'int_flow': int_flow, 'int_quant': int_quant, 
                                    'int_limit_min': int_limit_min, 'int_limit_max': int_limit_max,
                                    'min_flow': min_flow, 'min_quant': min_quant, 
                                    'min_limit_min': min_limit_min, 'min_limit_max': min_limit_max,})
singlejet_meter

,max_flow,max_quant,max_limit_min,max_limit_max,int_flow,int_quant,int_limit_min,int_limit_max,min_flow,min_quant,min_limit_min,min_limit_max
0.625,15,100,98.5,101.5,2,10,98.5,101.5,0.25,10,95,101.5
0.750,25,100,98.5,101.5,3,10,98.5,101.5,0.50,10,95,101.5
1.000,40,100,98.5,101.5,4,10,98.5,101.5,0.75,10,95,101.5
1.500,50,100,98.5,101.5,8,100,98.5,101.5,0.50,100,95,101.5
2.000,100,100,98.5,101.5,15,100,98.5,101.5,0.50,100,95,101.5
3.000,160,500,98.5,101.5,20,100,98.5,101.5,0.50,100,95,101.5
4.000,250,500,98.5,101.5,40,100,98.5,101.5,0.75,100,95,101.5
6.000,500,1000,98.5,101.5,60,100,98.5,101.5,1.50,100,95,101.5

### Fluid-Oscillator Meters

In [5]:
# Fluid-Oscillator Meters
size = [1/2, 5/8, 3/4, 1, 1 + 1/2, 2] #in
max_flow = [8, 15, 25, 40, 50, 100] #gpm
max_quant = [100, 100, 100, 100, 100, 100] #gal
max_limit_min = [98.5, 98.5, 98.5, 98.5,  98.5, 98.5] #%
max_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5, 101.5] #%
int_flow = [2, 2, 3, 4, 8, 15] #gpm
int_quant = [10, 10, 10, 10, 100, 100] #gal
int_limit_min = [98.5, 98.5, 98.5, 98.5,  98.5, 98.5] #%
int_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5, 101.5] #%
min_flow = [1/4, 1/4, 1/2, 3/4, 1 +  1/2, 2] #gpm
min_quant = [10, 10, 10, 10, 100, 100] #gal
min_limit_min = [95, 95, 95, 95, 95, 95] #%
min_limit_max = [101, 101, 101, 101, 101, 101] #%
fluid_oscillator_meter = pd.DataFrame(index = size, data = {'max_flow': max_flow, 'max_quant': max_quant, 
                                    'max_limit_min': max_limit_min, 'max_limit_max': max_limit_max, 
                                    'int_flow': int_flow, 'int_quant': int_quant, 
                                    'int_limit_min': int_limit_min, 'int_limit_max': int_limit_max,
                                    'min_flow': min_flow, 'min_quant': min_quant, 
                                    'min_limit_min': min_limit_min, 'min_limit_max': min_limit_max,})
fluid_oscillator_meter

,max_flow,max_quant,max_limit_min,max_limit_max,int_flow,int_quant,int_limit_min,int_limit_max,min_flow,min_quant,min_limit_min,min_limit_max
0.500,8,100,98.5,101.5,2,10,98.5,101.5,0.25,10,95,101
0.625,15,100,98.5,101.5,2,10,98.5,101.5,0.25,10,95,101
0.750,25,100,98.5,101.5,3,10,98.5,101.5,0.50,10,95,101
1.000,40,100,98.5,101.5,4,10,98.5,101.5,0.75,10,95,101
1.500,50,100,98.5,101.5,8,100,98.5,101.5,1.50,100,95,101
2.000,100,100,98.5,101.5,15,100,98.5,101.5,2.00,100,95,101

###  Class 1 Turbine Meters

In [6]:
# Class 1 Turbine Meters
size = [3/4, 1, 1 + 1/2, 2, 3, 4, 6] #in
max_flow = [30, 50, 100, 160, 350, 600, 1250] #gpm
max_quant = [100, 100, 500, 500, 1000, 1500, 4000] #gal
max_limit_min = [98, 98, 98, 98, 98, 98, 98] #%
max_limit_max = [102, 102, 102, 102, 102, 102, 102] #%
int_flow = [3, 5, 10, 16, 35, 60, 125] #gpm
int_quant = [10, 10, 100, 100, 100, 100, 1000] #gal
int_limit_min = [98, 98, 98, 98, 98, 98, 98] #%
int_limit_max = [102, 102, 102, 102, 102, 102, 102] #%
min_flow = [1 + 1/2, 2, 3, 4, 6, 8, 15] #gpm
min_quant = [10, 10, 100, 100, 100, 100, 1000] #gal
min_limit_min = [98, 98, 98, 98, 98, 98, 98] #%
min_limit_max = [102, 102, 102, 102, 102, 102, 102] #%
class1_turbine_meter = pd.DataFrame(index = size, data = {'max_flow': max_flow, 'max_quant': max_quant, 
                                    'max_limit_min': max_limit_min, 'max_limit_max': max_limit_max, 
                                    'int_flow': int_flow, 'int_quant': int_quant, 
                                    'int_limit_min': int_limit_min, 'int_limit_max': int_limit_max,
                                    'min_flow': min_flow, 'min_quant': min_quant, 
                                    'min_limit_min': min_limit_min, 'min_limit_max': min_limit_max,})
class1_turbine_meter

,max_flow,max_quant,max_limit_min,max_limit_max,int_flow,int_quant,int_limit_min,int_limit_max,min_flow,min_quant,min_limit_min,min_limit_max
0.75,30,100,98,102,3,10,98,102,1.5,10,98,102
1.00,50,100,98,102,5,10,98,102,2.0,10,98,102
1.50,100,500,98,102,10,100,98,102,3.0,100,98,102
2.00,160,500,98,102,16,100,98,102,4.0,100,98,102
3.00,350,1000,98,102,35,100,98,102,6.0,100,98,102
4.00,600,1500,98,102,60,100,98,102,8.0,100,98,102
6.00,1250,4000,98,102,125,1000,98,102,15.0,1000,98,102

### Class 2 Tubrine Meters

In [9]:
# Class 2 Turbine Meters
size = [1 + 1/2, 2, 3, 4, 6, 8, 10, 12, 16, 20] #in
max_flow = [100, 160, 350, 630, 1400, 2400, 3800, 5000, 10000, 15000] #gpm
max_quant = [500, 500, 1000, 1500, 4000, 7000, 10000, 15000, 30000, 40000] #gal
max_limit_min = [98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5] #%
max_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5] #%
int_limit_min = [98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5] #%
int_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5] #%
min_flow = [4, 4, 8, 15, 30, 50, 75, 120, 200, 300] #gpm
min_quant = [100, 100, 100, 100, 1000, 1000, 1000, 1000, 1000, 1000] #gal
min_limit_min = [98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5, 98.5] #%
min_limit_max = [101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5, 101.5] #%
class2_turbine_meter = pd.DataFrame(index = size, data = {'max_flow': max_flow, 'max_quant': max_quant, 
                                    'max_limit_min': max_limit_min, 'max_limit_max': max_limit_max, 
                                    'int_limit_min': int_limit_min, 'int_limit_max': int_limit_max,
                                    'min_flow': min_flow, 'min_quant': min_quant, 
                                    'min_limit_min': min_limit_min, 'min_limit_max': min_limit_max,})
class2_turbine_meter

,max_flow,max_quant,max_limit_min,max_limit_max,int_limit_min,int_limit_max,min_flow,min_quant,min_limit_min,min_limit_max
1.5,100,500,98.5,101.5,98.5,101.5,4,100,98.5,101.5
2.0,160,500,98.5,101.5,98.5,101.5,4,100,98.5,101.5
3.0,350,1000,98.5,101.5,98.5,101.5,8,100,98.5,101.5
4.0,630,1500,98.5,101.5,98.5,101.5,15,100,98.5,101.5
6.0,1400,4000,98.5,101.5,98.5,101.5,30,1000,98.5,101.5
8.0,2400,7000,98.5,101.5,98.5,101.5,50,1000,98.5,101.5
10.0,3800,10000,98.5,101.5,98.5,101.5,75,1000,98.5,101.5
12.0,5000,15000,98.5,101.5,98.5,101.5,120,1000,98.5,101.5
16.0,10000,30000,98.5,101.5,98.5,101.5,200,1000,98.5,101.5
20.0,15000,40000,98.5,101.5,98.5,101.5,300,1000,98.5,101.5

### Compound Meters

In [7]:
# Compound Meters
size = [2, 3, 4, 6, 8, 10] #in
max_flow = [160, 320, 500, 1000, 1600, 2300] #gpm
max_quant = [400, 1000, 1500, 3000, 4000, 4000] #gal
max_limit_min_class1 = [97, 97, 97, 97, 97, 97] #%
max_limit_max_class1 = [103, 103, 103, 103, 103, 103] #%
max_limit_min_class2 = [98.5, 98.5, 98.5, 98.5,  98.5, 98.5] #%
max_limit_max_class2 = [101.5, 101.5, 101.5, 101.5, 101.5, 101.5] #%
change_over_limit_min = [90, 90, 90, 90, 90, 90] #%
change_over_limit_max = [103, 103, 103, 103, 103, 103] #%
min_limit_min = [95, 95, 95, 95, 95, 95] #%
min_limit_max = [101, 101, 101, 101, 101, 101] #%
compound_meter = pd.DataFrame(index = size, data = {'max_flow': max_flow, 'max_quant': max_quant, 
                                    'max_limit_min_class1': max_limit_min_class1, 'max_limit_max_class1': max_limit_max_class1,
                                    'max_limit_min_class2': max_limit_min_class2, 'max_limit_max_class2': max_limit_max_class2,
                                    'change_over_limit_min': change_over_limit_min, 'change_over_limit_max': change_over_limit_max, 
                                    'min_limit_min': min_limit_min, 'min_limit_max': min_limit_max,})
compound_meter

,max_flow,max_quant,max_limit_min_class1,max_limit_max_class1,max_limit_min_class2,max_limit_max_class2,change_over_limit_min,change_over_limit_max,min_limit_min,min_limit_max
2,160,400,97,103,98.5,101.5,90,103,95,101
3,320,1000,97,103,98.5,101.5,90,103,95,101
4,500,1500,97,103,98.5,101.5,90,103,95,101
6,1000,3000,97,103,98.5,101.5,90,103,95,101
8,1600,4000,97,103,98.5,101.5,90,103,95,101
10,2300,4000,97,103,98.5,101.5,90,103,95,101